### ISSUE TITLE
Using pre-trained models directly to predict on example text

### ISSUE THREAD

**Issue by Lahssiniabdel** [dmis-lab/bern#10]
Hello, thank you for this great and very useful project.

I am a machine learning student, but I am not used to work with the first version of tensorflow. 
I am trying to use your pre-trained model for NER (I want to recognize diseaes, drugs and genes) instead of using your code to setup the API server. 

So I downloaded your pre-trained model in the pretrainedBERT folder, but I don't know how to upload the file model.ckpt for each type of named entities and especially how to use it to predict on a text example.

Can you please enlighten me on this point?

Many thanks in advance for your help !

**Comment by donghyeonk** [comment]
Thank you for your interest.

For BioBERT NER, you might want to look [here](https://github.com/dmis-lab/biobert#named-entity-recognition-ner). 

Have a nice day!
