### ISSUE TITLE
Running BERN on Windows: requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by ianovski** [dmis-lab/bern#15]
Hello,

Firstly, thank you so much for this project. I am really looking forward to using it.

I have been trying to run the sample code in the README on Windows, but I get the following connection error:

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8888): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020CE329CE88>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))`

The server appears to start running successfully when I use the following command:

`nohup python -u server.py --port 8888 --gnormplus_home GNormPlusJava/GNormPlusJava --gnormplus_port 18895 --tmvar2_home tmVarJava --tmvar2_port 188956 >> logs/nohup_BERN.out 2>&1 &`

Log output:
`tail -F logs/nohup_BERN.out`

```
INFO:tensorflow:_TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
BioBERT init_t 1.040 sec.
[19/Apr/2020 22:26:03.602298] Starting server at http://0.0.0.0:8888
gid2oid loaded 59849
goid2goid loaded 3468
gene meta #ids 42916, #ext_ids 42916
disease meta #ids 12122, #ext_ids 15040
chem meta #ids 179063, #ext_ids 179463
code2mirs size 9447
mirbase_id2mirna_id size 14945
mirna_id2accession size 6308
# of pathway regex 514
```

Would you have any suggestions to get this running? I followed all of the steps in the README but for Windows. Thank you!

**Comment by donghyeonk** [comment]
Thank you for your interest and report.

It is recommended to run BERN on Ubuntu. By the way, is port number 188956 configurable in Windows?

**Comment by ianovski** [comment]
Thanks for the suggestion @donghyeonk.

Windows doesn't allow port configuration for ports > 65535. This could be the problem.

I will give Ubuntu a try as well
