### ISSUE TITLE
KeyError: 'disease'

### ISSUE THREAD

**Issue by jamshaidsohail5** [dmis-lab/bern#19]
Hi. I was able to set up the repo successfully and also resolved the PubTator File not found error from #4 . Now I am getting the below error. 
![issue](https://user-images.githubusercontent.com/30027865/80966534-1fb7cb00-8e2e-11ea-9242-b151aca31efe.PNG)

If I scroll above a little in the terminal. I am getting this. 

![issue1](https://user-images.githubusercontent.com/30027865/80966625-48d85b80-8e2e-11ea-9f83-366de2e6fedd.PNG)

Any help would be highly appreciated.

**Comment by jamshaidsohail5** [comment]
The command below didn't download the pre-trained models in the above directory so I had to manually download it by opening the script file and getting the Google drive link. After that I placed the downloaded file in the respective directory as mentioned above and it worked.

sh download_biobert_ner_models.sh

**Comment by huangdanqi** [comment]
@jamshaidsohail5 
hello, I have the same problem. 
I do the "sh download_biobert_ner_models.sh", however, it can not solve my problem.

Here is my error. I hope you can give some advice.
![image](https://user-images.githubusercontent.com/55190597/122004689-4f822200-cde7-11eb-9279-52ffd3d89a6e.png)

![image](https://user-images.githubusercontent.com/55190597/122004737-5f9a0180-cde7-11eb-9bc1-92e68257088d.png)

**Comment by jamshaidsohail5** [comment]
Hi. Open  this file "[download_biobert_ner_models.sh](https://github.com/dmis-lab/bern/blob/master/scripts/download_biobert_ner_models.sh)" in notepad and then understand. You would see the google drive links of the models. Just download them and place them in the respective directory as the bash file is doing. Then repeat the process. You will see that the error will go away :)

**Comment by huangdanqi** [comment]
Thank you for your answer. I will try it!😊
