### ISSUE TITLE
Predictions overlapping

### ISSUE THREAD

**Issue by cszer** [dmis-lab/bern#2]
Helloy,thank you for this great project.I also working at my own ner for bio and the main issue now is predictions overlapping.If you can please describe the process how do you solve this problem

**Comment by donghyeonk** [comment]
Hi @cszer 
Thank you for your interest.

“First, if the entities do not overlap completely (71.3% in our dataset), BERN tags all the entities. If entities overlap completely and there is a mutation among the entities (0.5% (28.7% ×1.9 %)), BERN tags the mutation and entities that the mentions are most likely to be entities predicted by BioBERT NER models. Next, if entities completely overlap and all the entities are non-mutations (28.2% (28.7% ×98.1 %)), only the entities with the highest probability of being an actual entity are tagged”

For more detail, please see Section 3. B. 2) Decision rules of the paper.
https://ieeexplore.ieee.org/document/8730332

Have a nice day.

**Comment by cszer** [comment]
Thank you for answer.I decide to use vote rule based on f1 score of paritcular CRF head,that means when predictions ovelap we choose entity from head which has best f1 score.Do you think it is a good idea or i need to use more complex rule?

**Comment by donghyeonk** [comment]
Do you mean voting using the results of several CRFs with high f1? Can each CRF produce different results for the same input? If both are yes, it seems to be make sense.
