### ISSUE TITLE
Ending index is not correct in JSON for species category

### ISSUE THREAD

**Issue by NarenInD** [dmis-lab/bern#30]
@jhyuklee @donghyeonk @wonjininfo @seanswyi 
The starting index is correct, but the ending index is not correct for **species** category when getting the output from **api hit**

After the getting the start and end index, if I map it to word, the output is throw as below
sample output:  ["woma", "infan", "patien", "patien", "patien"]

The probelm is only in **Species** category, other categories are working correctly

**Comment by donghyeonk** [comment]
@NarenInD Thank you for your bug report. We fixed the bug. https://github.com/dmis-lab/bern/commit/198eeff6476c42c2dcfb67392f44a70d952a0e4f
