### ISSUE TITLE
Server offline

### ISSUE THREAD

**Issue by shoaibb** [dmis-lab/bern#44]
The bern server [https://bern.korea.ac.kr/](https://bern.korea.ac.kr/) is offline for the last couple of days. Any updates when it will be online again?

**Comment by minstar** [comment]
Sorry for the late reply.
BERN server was temporarily shut down due to a heat issue with the server itself.
We will solve this problem as soon as possible.

**Comment by minstar** [comment]
We were now open our server.
Sorry for the inconvenience.
