### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by JaskaranKaurGill** [dmis-lab/bern#48]
@jhyuklee 

The website seems to be down from couple of days. 

I have been getting following error 

`HTTPSConnectionPool(host='bern.korea.ac.kr', port=443): Max retries exceeded with url: /plain (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BE255B4550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

Is it going to be down for a while? if so, is there any other easy way to user BERN for NER without having to clone the whole repo?

**Comment by jhyuklee** [comment]
Hi, it should be on again. Our server was unstable due to the power outage.

**Comment by jhyuklee** [comment]
Besides, if you want to use the online website, BERN2 might be a better choice: http://bern2.korea.ac.kr/ (https://github.com/dmis-lab/BERN2)
