### ISSUE TITLE
What does the start and end tag in entities represent?

### ISSUE THREAD

**Issue by shivanik96** [dmis-lab/bern#5]
In the annotated PubMed data that you have shared, what do the 'start' and 'end' tag in 'entities' represent? Initially, I thought that they were character position but now I am not so sure. Can you please confirm.

**Comment by shivanik96** [comment]
I hit and tried various combinations and found out that the 'start' and 'end' tags in 'entities' actually are character offsets but they are not of the abstract, as I earlier thought. In fact, the offsets are calculated by appending title and abstract together separated by a tab.

**Comment by donghyeonk** [comment]
Hi @shivanik96 

Sorry for the late reply. 

Character-based indexes are provided for a string concating title and abstract.

We'll double check that there is no problem with that character-based index.

Thank you.

**Comment by shivanik96** [comment]
Hey @donghyeonk 
In the concatenated string, I think there is a tab in between the title and the abstract. Is it correct?

**Comment by donghyeonk** [comment]
@shivanik96 There is a space (i.e., " ") between the title and the abstract.

**Comment by shivanik96** [comment]
@donghyeonk thank you so much for your prompt replies. You guys have done great work.
