### ISSUE TITLE
Guide to fine-tune!

### ISSUE THREAD

**Issue by AndreasSaka** [dmis-lab/bern#6]
Dear authors!

Your work with Bern is amazing. I am still quite new to the domain of pre-trained/fine-tuned models! Is there an approach/guide/manual to fine-tune the pre-trained model on an (unstructured) dataset of our own?  Thanks in advance for your efforts!

**Comment by jhyuklee** [comment]
Hi @AndreasSaka,
please check [the BioBERT repository](https://github.com/dmis-lab/biobert) for fine-tuning your models on your dataset. For pre-training see [here](https://github.com/google-research/bert). Thanks!
