### ISSUE TITLE
Only Abstracts are getting tagged

### ISSUE THREAD

**Issue by nakumgaurav** [dmis-lab/bern#9]
Hi, it seems that BERN can only detects entities in the abstracts of the PubMed articles. Can it not tag the full article?

**Comment by donghyeonk** [comment]
Unfortunately, the XML structure of each article available from PubMed Central is so diverse that BERN does not yet support PubMed Central (full article). Note that there is a way to use PubTator Central (https://www.ncbi.nlm.nih.gov/research/pubtator/?view=docsum&query=PMC6389904) for full article tagging instead.
